#!/usr/bin/env python3
"""
Generates bis_data.lua from lgallucci/LoonBestInSlot.

Pulls per-spec guide files from the master_wotlk and master_tbc branches,
extracts every LBIS:AddItem(...) entry, and emits a single Lua table mapping
item entry -> list of Loot Arbiter spec names the item is BiS or Alt for.

Re-run this whenever you want to refresh against upstream:

    python3 tools/build_bis_data.py
"""

import re
import sys
import urllib.request
from pathlib import Path

# LoonBestInSlot guide filename stem -> Loot Arbiter spec name.
# Hunter/Rogue/Warlock collapse three trees to one spec because the arbiter
# script doesn't differentiate them.
LBIS_TO_ARBITER = {
    "DeathKnightBlood":    "DK Blood",
    "DeathKnightFrost":    "DK Frost",
    "DeathKnightUnholy":   "DK Unhol",
    "DruidBalance":        "Druid Bal",
    "DruidBear":           "Druid Bear",
    "DruidCat":            "Druid Cat",
    "DruidRestoration":    "Druid Resto",
    "HunterBeastMastery":  "Hunter",
    "HunterMarksmanship":  "Hunter",
    "HunterSurvival":      "Hunter",
    "MageArcane":          "Mage Arcane",
    "MageFire":            "Mage Fire",
    "MageFrost":           "Mage Frost",
    "PaladinHoly":         "Pally Holy",
    "PaladinProtection":   "Pally Prot",
    "PaladinRetribution":  "Pally Ret",
    "PriestDiscipline":    "Prst Disc",
    "PriestHoly":          "Prst Holy",
    "PriestShadow":        "Prst Shad",
    "RogueAssassination":  "Rogue",
    "RogueCombat":         "Rogue",
    "RogueSubtlety":       "Rogue",
    "ShamanElemental":     "Shamy Ele",
    "ShamanEnhancement":   "Shamy Enh",
    "ShamanRestoration":   "Shamy Resto",
    "WarlockAffliction":   "Warlock",
    "WarlockDemonology":   "Warlock",
    "WarlockDestruction":  "Warlock",
    "WarriorArms":         "War Arms",
    "WarriorFury":         "War Fury",
    "WarriorProtection":   "War Prot",
}

# TBC has no Death Knight, no Discipline priest guide, and a single
# combined Rogue DPS file instead of three per-tree files.
TBC_SKIP = {
    "DeathKnightBlood", "DeathKnightFrost", "DeathKnightUnholy",
    "PriestDiscipline",
    "RogueAssassination", "RogueCombat", "RogueSubtlety",
}
TBC_EXTRA = {
    "RogueDps": "Rogue",
}

BRANCHES = [
    ("master_wotlk", set(),    {}),
    ("master_tbc",   TBC_SKIP, TBC_EXTRA),
]

URL_TMPL = ("https://raw.githubusercontent.com/lgallucci/LoonBestInSlot/"
            "{branch}/LoonBestInSlot/Guides/{stem}.lua")

ITEM_RE = re.compile(
    r'LBIS:AddItem\(spec\d+,\s*"(\d+)"\s*,\s*LBIS\.L\["[^"]+"\]\s*,\s*"(BIS|Alt)"\)'
)


def fetch(branch: str, stem: str) -> str | None:
    url = URL_TMPL.format(branch=branch, stem=stem)
    req = urllib.request.Request(url, headers={"User-Agent": "loot-arbiter-bis-gen/1.0"})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return r.read().decode("utf-8", errors="replace")
    except Exception as e:
        print(f"  skip {stem}: {e}", file=sys.stderr)
        return None


def main() -> int:
    overrides: dict[int, set[str]] = {}
    file_counts: dict[str, int] = {}

    for branch, skip, extra in BRANCHES:
        print(f"== {branch} ==")
        per_branch = {**{k: v for k, v in LBIS_TO_ARBITER.items() if k not in skip}, **extra}
        for stem, arbiter_spec in per_branch.items():
            text = fetch(branch, stem)
            if text is None:
                continue
            matches = ITEM_RE.findall(text)
            n = 0
            for item_id, _rarity in matches:
                iid = int(item_id)
                overrides.setdefault(iid, set()).add(arbiter_spec)
                n += 1
            file_counts[f"{branch}:{stem}"] = n
            print(f"  {stem:<22} -> {arbiter_spec:<14} {n:>4} entries")

    print()
    print(f"Unique items across both expansions: {len(overrides)}")

    out_path = Path(__file__).resolve().parent.parent / "bis_data.lua"
    lines = [
        "-- AUTO-GENERATED by tools/build_bis_data.py.",
        "-- Source: github.com/lgallucci/LoonBestInSlot (master_wotlk + master_tbc).",
        "-- Map: item entry -> list of Loot Arbiter spec names the item is BiS/Alt for.",
        "-- Edit the generator, not this file. Regenerate to refresh against upstream.",
        "",
        "LootArbiter_BIS_OVERRIDES = {",
    ]
    for iid in sorted(overrides):
        specs = ", ".join(f'"{s}"' for s in sorted(overrides[iid]))
        lines.append(f"    [{iid}] = {{{specs}}},")
    lines.append("}")
    lines.append("")

    out_path.write_text("\n".join(lines))
    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
